# Generated by Django 2.2 on 2020-01-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='news',
            name='icon',
            field=models.ImageField(null=True, upload_to='', verbose_name='иконка'),
        ),
        migrations.AddField(
            model_name='news',
            name='url_source',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='ссылка на ресурс'),
        ),
    ]
